### ISSUE TITLE
Provider throwing error down the tree

### ISSUE THREAD

**Issue by iwishiwasaneagle** [rrousselGit/provider#181]
As far as I can tell I have followed the code from the [example](https://pub.dev/packages/provider#-example-tab-) to a T, but quite frankly I have no clue why I'm getting this error.

Log
```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 1,108ms.
I/flutter ( 4590): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4590): The following ProviderNotFoundError was thrown building CrowdTrailRoot(dirty):
I/flutter ( 4590): Error: Could not find the correct Provider<UserRepository> above this CrowdTrailRoot Widget
I/flutter ( 4590): 
I/flutter ( 4590): To fix, please:
I/flutter ( 4590): 
I/flutter ( 4590):   * Ensure the Provider<UserRepository> is an ancestor to this CrowdTrailRoot Widget
I/flutter ( 4590):   * Provide types to Provider<UserRepository>
I/flutter ( 4590):   * Provide types to Consumer<UserRepository>
I/flutter ( 4590):   * Provide types to Provider.of<UserRepository>()
I/flutter ( 4590):   * Always use package imports. Ex: `import 'package:my_app/my_code.dart';
I/flutter ( 4590):   * Ensure the correct `context` is being used.
I/flutter ( 4590): 
I/flutter ( 4590): If none of these solutions work, please file a bug at:
I/flutter ( 4590): https://github.com/rrousselGit/provider/issues
I/flutter ( 4590): 
I/flutter ( 4590): When the exception was thrown, this was the stack:
I/flutter ( 4590): #0      Provider.of (package:provider/src/provider.dart:227:7)
I/flutter ( 4590): #1      CrowdTrailRoot.build (package:crowdtrail/pages/root.dart:26:42)
I/flutter ( 4590): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3974:28)
I/flutter ( 4590): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
I/flutter ( 4590): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4590): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 4590): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 4590): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 4590): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 4590): #9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
I/flutter ( 4590): #10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
I/flutter ( 4590): #11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
I/flutter ( 4590): #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter ( 4590): #13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
I/flutter ( 4590): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter ( 4590): #15     runApp (package:flutter/src/widgets/binding.dart:786:7)
I/flutter ( 4590): #16     main (package:crowdtrail/main.dart:8:16)
I/flutter ( 4590): #17     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
I/flutter ( 4590): #22     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
I/flutter ( 4590): #23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
I/flutter ( 4590): #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter ( 4590): (elided 4 frames from package dart:async)
I/flutter ( 4590): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
`main.dart`
```
import 'package:flutter/material.dart';

import 'package:crowdtrail/pages/root.dart';
import 'package:crowdtrail/pages/authentication/UserRepository.dart';

import 'package:provider/provider.dart';

void main() => runApp(CrowdTrailRoot());

class CrowdTrail extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [ChangeNotifierProvider(builder:(_)=>UserRepository())],
        child: MaterialApp(
        title: 'CrowdTrail',
        theme: ThemeData(
          primarySwatch: Colors.orange,
        ),
        home:
             const CrowdTrailRoot(),
        ));
  }
}
```
`root.dart`
```
import 'package:flutter/material.dart';

import 'package:crowdtrail/pages/homePages/homePage.dart';
import 'package:crowdtrail/pages/authentication/UserRepository.dart';
import 'package:crowdtrail/pages/splash.dart';

import 'package:provider/provider.dart';

class CrowdTrailRoot extends StatelessWidget {

  const CrowdTrailRoot();

  //class CrowdTrailRoot extends StatefulWidget {
//  CrowdTrailRoot({Key key}) : super(key: key);
//
//  @override
//  _CrowdTrailRootState createState() => _CrowdTrailRootState();
//}
//
//class _CrowdTrailRootState extends State<CrowdTrailRoot>{



  @override
  Widget build(BuildContext context) {
    final UserRepository user = Provider.of<UserRepository>(context);
    switch (user.status){
      case Status.Uninitialized:
        return Splash();
      case Status.Authenticated:
        return CrowdTrailHome();
      case Status.Authenticating:
      case Status.Unauthenticated:
        return Center(child: Text("Hi"),);
    }
    return Center(child:Text("UwU thewe's bween an ewwow... Senpai will fix it swoon!"));
  }
}
```
`UserRepository.dart`
```
import 'package:flutter/material.dart';

enum Status { Uninitialized, Authenticated, Authenticating, Unauthenticated }

class UserRepository with ChangeNotifier {
  Status _status = Status.Uninitialized;
  Status get status => _status;
}
```

**Comment by rrousselGit** [comment]
Looking at your code, your `main` start the app with `CrowdTrailRoot`. But you likely wanted `CrowdTrail` instead

**Comment by iwishiwasaneagle** [comment]
Worked a treat. Cheers! Can't believe I missed such a simple fix...
