### ISSUE TITLE
To safely refer to a widget's ancestor in its dispose()

### ISSUE THREAD

**Issue by MahdiPishguy** [rrousselGit/provider#214]
Hi Remi, i have a problem with this error and i can't resolve that

in `main` function i defined this providers:

```dart
...  
MultiProvider(providers: [
  Provider(builder: (_) => database),
  Provider(builder: (_) => database.userTableDao),
  Provider(builder: (_) => settings),
] ...  ,
```

and into `register_navigator` i have `TabBarView` with two children

```dart
FutureBuilder(
    future: Provider.of<UserTableDao>(context).getSingleUser(),
    builder: (context, snapshot) {
      if (snapshot.connectionState == ConnectionState.done) {
        UserTableData user = snapshot.data;
        ...
        TabBarView( ... ),
      }

      ...
}),
```

in one page of `TabBarView` page, when i try to use `Provider` again such as :

```dart
Provider.of<UserTableDao>(event.context).insertUser();
```

i get this error

`To safely refer to a widget's ancestor in its dispose()`

WHEN I REMOVE PROVIDER IMPLEMENTATION FROM PARENT OF `TabBarView` THAT CAUSE OF REOLVING PROBLEM

**Comment by rrousselGit** [comment]
None of the snippets you added can trigger this exception.

Have you tried doing what the exception says? The error message contains the fix to the issue

**Comment by MahdiPishguy** [comment]
@rrousselGit the error messages is:

```dart
I/flutter (21506): INFO: 2019-09-07 23:10:11.202217: --> END POST (15413-byte body)
E/flutter (21506): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (21506): At this point the state of the widget's element tree is no longer stable.
E/flutter (21506): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (21506): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3389:9)
E/flutter (21506): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3403:6)
E/flutter (21506): #2      Element.inheritFromWidgetOfExactType (package:flutter/src/widgets/framework.dart:3418:12)
E/flutter (21506): #3      Provider.of (package:provider/src/provider.dart:255:19)
E/flutter (21506): #4      RegisterRepository.createUser (package:diabetist_pro/screens/fragments/fragmemt_register/view/partials/register_account/repository/register_repository.dart:22:14)
E/flutter (21506): <asynchronous suspension>
E/flutter (21506): #5      RegisterBloc.mapEventToState (package:diabetist_pro/screens/fragments/fragmemt_register/view/partials/register_account/bloc/register_bloc.dart:25:30)
E/flutter (21506): <asynchronous suspension>
E/flutter (21506): #6      Bloc._bindStateSubject.<anonymous closure> (package:bloc/src/bloc.dart:127:14)
E/flutter (21506): #7      Stream.asyncExpand.onListen.<anonymous closure> (dart:async/stream.dart:513:30)
E/flutter (21506): #8      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (21506): #9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (21506): #10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (21506): #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (21506): #12     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (21506): #13     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter (21506): #14     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter (21506): #15     _rootRun (dart:async/zone.dart:1120:38)
E/flutter (21506): #16     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (21506): #17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (21506): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (21506): #19     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (21506): #20     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (21506): #21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (21506): #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (21506): #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (21506): #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

and `register_account/repository/register_repository.dart:22:14` is:

```dart
void createUser(BuildContext context, BuiltRegisterResponse body) async {
  Provider.of<UserTableDao>(context).insertUser(
  ...
  );
}
```

**Comment by MahdiPishguy** [comment]
@rrousselGit could you help me to resolve that? thanks

**Comment by rrousselGit** [comment]
The solution is in the error message: use `didChangeDependencies`.

If you're still having trouble with this, instead of an issue, consider posting this kind of question on [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or [Gitter](https://gitter.im/flutter_provider/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by casualcoder404** [comment]
@MahdiPishguy Have you resolved the issue?

**Comment by MahdiPishguy** [comment]
> 
> 
> @MahdiPishguy Have you resolved the issue?

no, in that time i can't

**Comment by comerc** [comment]
https://github.com/flutter/flutter/issues/11426#issuecomment-414047398

**Comment by AalaaNagy88** [comment]
I have the same issue do you find a solution?

**Comment by MahdiPishguy** [comment]
@AalaaNagy88 Regarding your issue, as i think about that i solve this problem. let me know if you can't solve that

**Comment by AalaaNagy88** [comment]
I can't resolve it.
The problem occurs when I push and replace the current screen. And the provider used its context.

**Comment by MahdiPishguy** [comment]
@AalaaNagy88 did you put Provider inside `didChangeDependencies` to initialize?

**Comment by AalaaNagy88** [comment]
No

**Comment by MahdiPishguy** [comment]
@AalaaNagy88 ok. so move it inside this function which can use `Context` there

**Comment by HannesGitH** [comment]
for everyone still facing the issue, the Provider is scoped to the current route, so with `navigator.push()` you lose all the providers.
to pass providers to the next route do:
```dart
Navigator.push(
  context,
  MaterialPageRoute(
    builder: (newcontext) => 
      ChangeNotifierProvider<YourModel>.value(
        value: Provider.of<YourModel>(context),
        child: newView,
      )
  ),
);
```

**Comment by TechGeekTR** [comment]
> @AalaaNagy88 ok. so move it inside this function which can use `Context` there

This answer salved my problem, thanks.

**Comment by mcadet** [comment]
Thank you @HannesGitH ! You saved my day.
