### ISSUE TITLE
I'm trying to log out with provider

### ISSUE THREAD

**Issue by gussouzauni** [rrousselGit/provider#246]
To fix, please:

  * Ensure the Provider<UserConfig> is an ancestor to this UserInfoScreen Widget
  * Provide types to Provider<UserConfig>
  * Provide types to Consumer<UserConfig>
  * Provide types to Provider.of<UserConfig>()
  * Always use package imports. Ex: `import 'package:my_app/my_code.dart';
  * Ensure the correct `context` is being used.

If none of these solutions work, please file a bug at:
https://github.com/rrousselGit/provider/issues
When the exception was thrown, this was the stack: 
#0      Provider.of (package:provider/src/provider.dart:260:7)
#1      UserInfoScreen.build.<anonymous closure> (package:duolingo_flutter/screens/user_screen.dart:20:22)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#8914a
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(398.8, 47.2)
  finalLocalPosition: Offset(35.4, 23.2)
  sent tap down

**Comment by gussouzauni** [comment]
appBar: AppBar(
        elevation: 0,
        actions: <Widget>[
         IconButton(
           icon: Icon(Icons.exit_to_app),
           onPressed: () {
            Provider.of<UserConfig>(context).signOut();
           },
         )
        ],
        title: Text("Usuário"),
      ),
