### ISSUE TITLE
How to stub Provider methods?

### ISSUE THREAD

**Issue by IoanaAlexandru** [rrousselGit/provider#365]
I couldn't find anything in the documentation about this particular testing case.

This is a simplified version of what I tried:

``` dart
class MyApp extends StatelessWidget {
  final AuthProvider authProvider;

  MyApp({AuthProvider authProvider})
      : this.authProvider = authProvider ?? AuthProvider();

  @override
  Widget build(BuildContext context) {
          return MultiProvider(
            providers: [
              ChangeNotifierProvider<AuthProvider>(
                  create: (_) => authProvider)
            ],
            child: MaterialApp(
                localizationsDelegates: [
                  GlobalMaterialLocalizations.delegate,
                  GlobalWidgetsLocalizations.delegate,
                  S.delegate
                ],
                supportedLocales: S.delegate.supportedLocales,
                home: AppNavigator()),
          );
  }
```

My `AuthProvider` class contains the following getter:
``` dart
bool get isAuthenticated {
    return user != null;
}
```

Which I'm trying to stub like this in my test file:

``` dart
class MockAuthProvider extends Mock implements AuthProvider {}

void main() {
      testWidgets('Test', (WidgetTester tester) async {
            AuthProvider mockAuthProvider = MockAuthProvider();
            when(mockAuthProvider.isAuthenticated).thenReturn(true);

            await tester.pumpWidget(MyApp(authProvider: mockAuthProvider));
            await tester.pumpAndSettle();
      }
}
```

And I get the following error when calling `Provider.of(context)` in `AppNavigator` (line 15):

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building AppNavigator(dirty, dependencies:
[_DefaultInheritedProviderScope<AuthProvider>], state: AppNavigatorState#e6c3b):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was:
  AppNavigator file:///C:/Users/sako_/StudioProjects/acs-upb-mobile/lib/main.dart:59:23

When the exception was thrown, this was the stack:
#0      new ListenableProvider.<anonymous closure> (package:provider/src/listenable_provider.dart:41:35)
#1      _CreateInheritedProviderState.value.<anonymous closure> (package:provider/src/inherited_provider.dart:409:48)
#2      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:411:10)
#3      _InheritedProviderScopeMixin.value (package:provider/src/inherited_provider.dart:295:33)
#4      Provider.of (package:provider/src/provider.dart:233:29)
#5      AppNavigatorState.build (package:acs_upb_mobile/navigation/navigator.dart:15:42)
...
```
<details>
<summary>The rest of the error</summary>
<p>

```
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4440:27)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4329:15)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
#33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
#46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#58     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
#59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#71     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
#78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#87     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#99     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
#100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#106    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#111    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#112    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
#113    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#114    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#115    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5684:32)
#116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#119    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#120    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#121    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
#122    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#127    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#131    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#132    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#133    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#135    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#136    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#137    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
#138    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#141    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#144    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#146    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#148    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#149    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#150    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#151    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#155    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#156    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
#157    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#158    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#161    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#162    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#163    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#168    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#180    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#185    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#189    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#191    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#193    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#197    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#198    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#199    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
#200    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#201    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#202    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#204    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#205    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#206    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#207    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#208    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#210    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#211    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#212    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#213    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#214    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#215    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#216    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#217    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#219    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#220    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#221    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#222    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#223    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#225    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#226    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#227    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#228    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#229    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#230    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#231    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#232    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#233    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#234    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#235    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#236    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#237    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#238    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#239    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#240    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#241    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#243    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#244    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
#245    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
#246    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#247    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#248    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
#249    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
#250    Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
#251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
#252    Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
#253    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2532:33)
#254    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1002:18)
#255    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#256    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1109:15)
#257    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1048:9)
#258    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:875:9)
#261    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#262    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:862:27)
#263    WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:542:23)
#265    WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:537:39)
#268    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#269    WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:537:27)
#270    main.<anonymous closure>.<anonymous closure> (file:///C:/Users/sako_/StudioProjects/acs-upb-mobile/test/navigation_test.dart:26:20)
#284    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1095:17)
#286    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1083:35)
(elided 34 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

</p>
</details>

**Comment by rrousselGit** [comment]
You should instead move your provider above `MyApp`.

This allows you to use `MyApp` with different providers

**Comment by IoanaAlexandru** [comment]
@rrousselGit I tried that and got the exact same result.

**Comment by rrousselGit** [comment]
You need to mock `hasListener` too:

```dart
when(mockAuthProvider.hasListener).thenReturn(false);
```

**Comment by IoanaAlexandru** [comment]
Wow I just figured that out 1 minute ago before seeing your reply. Thank you, that worked!
