### ISSUE TITLE
No instance method error

### ISSUE THREAD

**Issue by CripyIce** [rrousselGit/provider#372]
Hi there,
I made a custom object with the following code:
```dart
class BusinessCardModel {
  final int id;
  final String imagePath;

  BusinessCardModel({
    this.id,
    this.imagePath,
  });

  BusinessCardModel copyWith({
    int id,
    String imagePath,
  }) =>
      BusinessCardModel(
        id: id ?? this.id,
        imagePath: imagePath ?? this.imagePath,
      );

  factory BusinessCardModel.fromMap(Map<String, dynamic> json) =>
      BusinessCardModel(
        id: json["id"] == null ? null : json["id"],
        imagePath: json["image_path"] == null ? null : json["image_path"],
      );

  Map<String, dynamic> toMap() => {
        "id": id == null ? null : id,
        "image_path": imagePath == null ? null : imagePath,
      };
}
```

When trying to make an HTTP request using `Dio` I'm getting an error with the following code:
```dart
Provider.of<ApiProvider>(context, listen: false).updateBusinessCardDetails(data: Provider.of<BusinessCardModel>(context, listen: false).toMap());
```

the error:
```
Class '_InternalLinkedHashMap<String, dynamic>' has no instance method 'toMap'.
Receiver: _LinkedHashMap len:1
Tried calling: toMap()
```

Trying to print `Provider.of<BusinessCardModel>(context, listen: false).toMap()` also gives the same error.

When using `print(BusinessCardModel().toMap());` I don't get any errors and it works fine.

Please help!

**Comment by rrousselGit** [comment]
Are you sure that it is the line you gave that has the error? 

From the error message, the failing `toMap` was called on a `Map` not on `BusinessCarModel`

**Comment by CripyIce** [comment]
@rrousselGit Thanks for the fast reply!
This is `api_provider.dart`:
![image](https://user-images.githubusercontent.com/26387823/75983310-fa234980-5ef0-11ea-92e6-2b011dd8f388.png)
This is the error:
```
flutter:
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance method 'toMap'.
Receiver: _LinkedHashMap len:1
Tried calling: toMap()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      BusinessCardModel.toMap (package:ironclic/model/business_card_model.dart:441:53)
#2      ApiProvider.updateBusinessCardDetails (package:ironclic/remote/api_provider.dart:171:92)
#3      _BusinessCardEditTabDesignOneState.build.<anonymous closure> (package:ironclic/ui/business_card/business_card_edit_screen/design/business_card_edit_tab_design_one.dart:90:20)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:705:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:788:36)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:4<…>
```

**Comment by rrousselGit** [comment]
The exception is on line `441` of `business_card_model.dart`, not on the screenshot you gave

**Comment by CripyIce** [comment]
@rrousselGit , Now it seems to work fine without changing anything.
If issue will appear again I will reopen this ticket.
