### ISSUE TITLE
Using multiprovider giving compilation error without any stack trace. When I am commenting out multiprovider, the app is able to compile and working.

### ISSUE THREAD

**Issue by vivek781113** [rrousselGit/provider#418]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Unhandled exception:
Crash when compiling package:st_mgmt_provider/services/database_service.dart,
at character offset null:
NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)

#1      scannerRecovery  (package:_fe_analyzer_shared/src/scanner/recover.dart:29:17)
#2      _tokenizeAndRecover (package:_fe_analyz
er_shared/src/scanner/scanner.dart:102:14)

#3      scan  (package:_fe_analyzer_shared/src/scanner/scanner.dart:81:10)
#4      SourceLoader.tokenize  (package:front_end/src/fasta/source/source_loader.dart:220:28)
<asynchronous suspension>
#5      SourceLoader.buildOutline  (package:front_end/src/fasta/source/source_loader.dart:294:26)
<asynchronous suspension>

#6      Loader.buildOutlines  (package:front_end/src/fasta/loader.dart:255:13)
<asynchronous suspension>
#7      KernelTarget.buildOutlines.<anonymous closure>  (package:front_end/src/fasta/kernel/kernel_target.dart:257:20)
#8      withCrashReporting  (package:front_end/src/fasta/crash.dart:122:24)

#9      KernelTarget.buildOutlines  (package:front_end/src/fasta/kernel/kernel_target.dart:255:12)
#10     generateKernelInternal.<anonymous closure>  (package:front_end/src/kernel_generator_impl.dart:129:28)
<asynchronous suspension>
#11     withCrashReporting  (package:front_end/src/fasta/crash.dart:122:24)
![CommentedMuiltProvider](https://user-images.githubusercontent.com/32304458/79433715-1a175400-7feb-11ea-9015-b608fb7afb84.JPG)
[https://github.com/vivek781113/st_mgmt_provider.git](url)

**Comment by vivek781113** [comment]
Issue was related Little-endian UTF-16 Unicode text, with CRLF line terminators, after converting it to utf , 8 it's working

**Comment by vivek781113** [comment]
Issue was related to Little-endian UTF-16 Unicode text, with CRLF line terminators, after converting it to UTF 8 , it's working.

**Comment by vivek781113** [comment]
Issue was related to Little-endian UTF-16 Unicode text, with CRLF line terminators, after converting it to UTF 8 , it's working.
