### ISSUE TITLE
 The getter 'owner' was called on null.

### ISSUE THREAD

**Issue by lantongxue** [rrousselGit/provider#423]
Exception Message:
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'owner' was called on null.
Receiver: null
Tried calling: owner
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      Provider.of 
package:provider/src/provider.dart:193
#2      MainAppState.initConfig 
package:my_app/main.dart:137
#3      _asyncThenWrapperHelper.<anonymous closure>  (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary  (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue  (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners  (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue  (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.da<…>
```

Provider Version
```yaml
provider: ^4.0.5
```

main.dart
```dart
void main(){
 runApp(MyApp());
}
class MyApp extends StatelessWidget {
 @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AppProvider()),
      ],
      child: new MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Consumer<AppProvider>(
          builder: (context, appProvider, _){
            return MainApp();
          },
        ),
      ),
    );
  }
}
class MainApp extends StatefulWidget {
  @override
  MainAppState createState() {
    return new MainAppState();
  }
}
class MainAppState extends State<MainApp> {
// some code
@override
  void didChangeDependencies() {
    super.didChangeDependencies();
    scheduleMicrotask(this.initConfig);
  }
void initConfig() async{
    // some code
   var config = AppConfig(id: 1, title: 'test title');
    Provider.of<AppProvider>(context, listen: false).updateAppConfig(config); // Exception here
  }
}
```
AppProvider.dart
```dart
class AppProvider with ChangeNotifier {
  AppConfig _appConfig = AppConfig.empty();

  AppProvider();

  void updateAppConfig(AppConfig config){
    this._appConfig = config;
    notifyListeners();
  }

  get config => this._appConfig;
}
```
Found null `context` object through debugging.
How to solve this problem ?

**Comment by rrousselGit** [comment]
> Found null context object through debugging.
How to solve this problem ?

Don't pass `null` to `Provider.of`/`context.watch`

**Comment by lantongxue** [comment]
> > Found null context object through debugging.
> > How to solve this problem ?
> 
> Don't pass `null` to `Provider.of`/`context.watch`
`context` is the context of the current widget. How can it be null?

**Comment by rrousselGit** [comment]
> context is the context of the current widget. How can it be null?

It can be `null` after the widget was removed from the widget tree, so that's likely what happened to you

**Comment by lantongxue** [comment]
> > context is the context of the current widget. How can it be null?
> 
> It can be `null` after the widget was removed from the widget tree, so that's likely what happened to you

Ok, i fixed, it's my logic error.

**Comment by rcsousa14** [comment]
How did you solve this problem? can you provide the code please

**Comment by rcsousa14** [comment]
check if context != null figure it out here

**Comment by shirisha-96** [comment]
> > > context is the context of the current widget. How can it be null?
> > 
> > 
> > It can be `null` after the widget was removed from the widget tree, so that's likely what happened to you
> 
> Ok, i fixed, it's my logic error.

**Comment by gaoshanyu** [comment]
@rcsousa14 you fix me, you are the hero!

**Comment by dhonor** [comment]
666

**Comment by RagzDaBest** [comment]
I actually am very confused... I got a similar error, but I don't understand the solution... What do I have to do? Can you just give a piece of code for me to add..?
