### ISSUE TITLE
AssertionFailure when calling Provider.of() with listen = false

### ISSUE THREAD

**Issue by meiwin** [rrousselGit/provider#438]
Despite specifying `false` for the `listen` parameter when calling `Provider.of()`, an AssertionFailure is being thrown with message that says it should be invoked with `listen:false`.

```
The following assertion was thrown while handling a gesture:
Tried to listen to a value exposed with provider, from outside of the widget tree.

This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.

To fix, write:
Provider.of<FailingFixedLevel1>(context, listen: false);

It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.

The context used was: _DefaultInheritedProviderScope<FailingResource>(dependencies: [_DefaultInheritedProviderScope<FailingProxiedLevel1>], value: null)
'package:provider/src/provider.dart':
Failed assertion: line 193 pos 7: 'context.owner.debugBuilding || listen == false || _debugIsInInheritedProviderUpdate'
```

This appears to happen when looking up an object provided using `ProxyProvider` with lazy = `true` for the first time. The error goes away if the ProxyProvider constructor is specified with lazy = `false`.

I have created a simple repro case to demonstrate this issue that can be found below. Is there anything I missed, or is this possibly a bug? (Note: tested on provider 4.0.5+1)

```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: failedProviders,
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(primarySwatch: Colors.blue),
        home: MyHomePage(title: 'Flutter Demo Home Page'),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _triggerFailure() {
    // The following will throw AssertionError
    print(
        '_ProxiedResource0: ${Provider.of<FailingResource>(context, listen: false)}');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title)
      ),
      body: Center(
        child: Text('Press the button to trigger assertion failure')
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _triggerFailure,
        tooltip: 'Trigger Failure',
        child: Icon(Icons.error),
      ),
    );
  }
}

//////////////////// Following providers setup is failing

final failedProviders = [
  Provider.value(value: FailingFixedLevel1()),
  Provider.value(value: FailingFixedLevel2()),
  ProxyProvider<FailingFixedLevel2, FailingProxiedLevel1>(
    update: (context, dep0, previous) => FailingProxiedLevel1(dep0),
  ),
  ProxyProvider2<FailingProxiedLevel1, FailingFixedLevel1, FailingResource>(
    update: (context, dep0, dep1, previous) => FailingResource(dep0, dep1),
  ),
];

// Provider tree
//
// FailingResource
// \- FailingProxiedLevel1
//     \- FailingFixedLevel2
// \- FailingFixedLevel1

class FailingResource {
  FailingResource(this.dep0, this.dep1);

  final FailingProxiedLevel1 dep0;
  final FailingFixedLevel1 dep1;
}

class FailingProxiedLevel1 {
  FailingProxiedLevel1(this.dep0);

  final FailingFixedLevel2 dep0;
}

class FailingFixedLevel1 {}

class FailingFixedLevel2 {}
```

**Comment by rrousselGit** [comment]
Tested on 4.1.0 and this works for me. So this probably got fixed

Could you confirm?

**Comment by meiwin** [comment]
Tried on 4.1.0-dev+1 and still able to see the assertion error.

```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Tried to listen to a value exposed with provider, from outside of the widget tree.

This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.

To fix, write:
Provider.of<FailingFixedLevel1>(context, listen: false);

It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.

The context used was: _InheritedProviderScope<FailingResource>(dependencies: [_InheritedProviderScope<FailingProxiedLevel1>], value: null)
'package:provider/src/provider.dart':
Failed assertion: line 191 pos 7: 'context.owner.debugBuilding ||
          listen == false ||
          _debugIsInInheritedProviderUpdate'

When the exception was thrown, this was the stack: 
#2      Provider.of (package:provider/src/provider.dart:191:7)
#3      new ProxyProvider2.<anonymous closure> (package:provider/src/proxy_provider.dart:188:22)
#4      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:555:33)
#5      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:428:33)
#6      Provider.of (package:provider/src/provider.dart:216:29)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#f447f
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(378.3, 851.0)
  finalLocalPosition: Offset(36.3, 27.0)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by rrousselGit** [comment]
4.1.0-dev+1 is not the latest

Try 4.1.0

**Comment by meiwin** [comment]
Oh no wonder.

Yes, it works fine on 4.1.0.

Thanks!
