### ISSUE TITLE
Can't use context.read or context.watch for InkWell

### ISSUE THREAD

**Issue by feinstein** [rrousselGit/provider#556]
I have a list with lots of cards, this is the structure of each `Card`:

![image](https://user-images.githubusercontent.com/8120472/96068473-837d0000-0e72-11eb-9944-283b7932b26b.png)

In the `InkWell` `onTap` callback I am navigating to a new route:

```dart
onTap: () async {
  Navigator.push(
    context,
    MaterialPageRoute(
      builder: (context) {
        context.watch<AppViewModel>().selectedItem = item;
        return NextScreen();
      },
    ),
  );
},
```

If I use `context.read` I get an Error screen:

![image](https://user-images.githubusercontent.com/8120472/96068680-f8503a00-0e72-11eb-84da-c41bc30a91dc.png)

If I use `context.watch` I get a flutter error:

```
I/flutter ( 9359): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter ( 9359): The following assertion was thrown while dispatching notifications for AppViewModel:
I/flutter ( 9359): setState() or markNeedsBuild() called during build.
I/flutter ( 9359): This _InheritedProviderScope<AppViewModel> widget cannot be marked as needing to build because the
I/flutter ( 9359): framework is already in the process of building widgets.  A widget can be marked as needing to be
I/flutter ( 9359): built during the build phase only if one of its ancestors is currently building. This exception is
I/flutter ( 9359): allowed because the framework builds parent widgets before children, which means a dirty descendant
I/flutter ( 9359): will always be built. Otherwise, the framework might not visit this widget during this build phase.
I/flutter ( 9359): The widget on which setState() or markNeedsBuild() was called was:
I/flutter ( 9359):   _InheritedProviderScope<AppViewModel>
I/flutter ( 9359): The widget which was currently being built when the offending call was made was:
I/flutter ( 9359):   Builder
I/flutter ( 9359): 
I/flutter ( 9359): When the exception was thrown, this was the stack:
I/flutter ( 9359): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4292:11)
I/flutter ( 9359): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
I/flutter ( 9359): #2      _InheritedProviderScopeElement.markNeedsNotifyDependents (package:provider/src/inherited_provider.dart:491:5)
I/flutter ( 9359): #3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
I/flutter ( 9359): #4      AppViewModel.selectedItem= (package:myapp/view_models/AppViewModel.dart:36:7)
I/flutter ( 9359): #5      itemItem.build.<anonymous closure>.<anonymous closure> (package:myapp/screens/items_screen.dart:320:57)
I/flutter ( 9359): #6      MaterialPageRoute.buildContent (package:flutter/src/material/page.dart:55:55)
I/flutter ( 9359): #7      MaterialRouteTransitionMixin.buildPage (package:flutter/src/material/page.dart:108:27)
I/flutter ( 9359): #8      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:820:45)
I/flutter ( 9359): #9      Builder.build (package:flutter/src/widgets/basic.dart:7183:48)
I/flutter ( 9359): #10     StatelessElement.build (package:flutter/src/widgets/framework.dart:4701:28)
I/flutter ( 9359): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
I/flutter ( 9359): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 9359): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
I/flutter ( 9359): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
I/flutter ( 9359): ...     Normal element mounting (123 frames)
I/flutter ( 9359): #137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter ( 9359): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
I/flutter ( 9359): #139    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5705:32)
I/flutter ( 9359): #140    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
I/flutter ( 9359): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 9359): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter ( 9359): #143    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter ( 9359): #144    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 9359): #145    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter ( 9359): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 9359): #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter ( 9359): #148    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 9359): #149    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
I/flutter ( 9359): #150    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
I/flutter ( 9359): #151    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 9359): #152    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
I/flutter ( 9359): #153    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 9359): #154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter ( 9359): #155    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter ( 9359): #156    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 9359): #157    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter ( 9359): #158    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 9359): #159    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
I/flutter ( 9359): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 9359): #161    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
I/flutter ( 9359): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 9359): #163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter ( 9359): #164    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 9359): #165    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
I/flutter ( 9359): #166    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 9359): #167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter ( 9359): #168    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 9359): #169    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
I/flutter ( 9359): #170    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 9359): #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter ( 9359): #172    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter ( 9359): #173    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 9359): #174    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
I/flutter ( 9359): #175    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
I/flutter ( 9359): #176    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter ( 9359): #177    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter ( 9359): #178    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter ( 9359): #179    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter ( 9359): #183    _invoke (dart:ui/hooks.dart:251:10)
I/flutter ( 9359): #184    _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter ( 9359): (elided 3 frames from dart:async)
I/flutter ( 9359): 
I/flutter ( 9359): The AppViewModel sending notification was:
I/flutter ( 9359):   Instance of 'AppViewModel'
I/flutter ( 9359): ════════════════════════════════════════════════════════════════════════════════════════════════════
````

**Comment by feinstein** [comment]
Ok, never mind, this error was on my side of things.
