### ISSUE TITLE
[iOS+Android]: Null check operator used on a null value

### ISSUE THREAD

**Issue by Ahmadre** [rrousselGit/provider#677]
**Describe the bug**
I recognized that in some cases Provider runs into a null check error:

<img width="939" alt="Bildschirmfoto 2021-09-04 um 17 32 40" src="https://user-images.githubusercontent.com/18512224/132100032-4dbee251-02c8-4f46-bb5c-cc9bb58918af.png">

**To Reproduce**
![carbon (6)](https://user-images.githubusercontent.com/18512224/132100165-ee5247bc-61c1-41a5-88f6-22161581b078.png)

Is also use this dispose in my AudioNotifier:

```dart
@override
void dispose() {
  _player.dispose();
  super.dispose();
}
```

**Expected behavior**
Provider shouldn't run into the mentioned null check operator error. Maybe I am doing something wrong here?

**Comment by rrousselGit** [comment]
Do you have a reliable way to reproduce the issue? And what version did you use? 

The stacktrace isn't pointing to anything meaningful

**Comment by Ahmadre** [comment]
> Do you have a reliable way to reproduce the issue? And what version did you use?
> 
> The stacktrace isn't pointing to anything meaningful

Oh, yes! Sorry for the lack of infos 😄 . 

Actually I could reproduce it with a fresh new Flutter project. You can check it out here: https://github.com/Ahmadre/AudioProviderTest

## Version

```yaml
provider: ^6.0.0
```

## Full Stacktrace

```sh
════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown while finalizing the widget tree:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      Element.widget
package:flutter/…/widgets/framework.dart:3129
#1      Provider._inheritedElementOf
package:provider/src/provider.dart:343
#2      Provider.of
package:provider/src/provider.dart:295
#3      _AudioScreenState.dispose
package:app/audio_screen/audio_screen.dart:34
#4      StatefulElement.unmount
package:flutter/…/widgets/framework.dart:4895
#5      _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1883
#6      _InactiveElements._unmount.<anonymous closure>
package:flutter/…/widgets/framework.dart:1881
#7      SingleChildRenderObjectElement.visitChildren
package:flutter/…/widgets/framework.dart:6182
#8      _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1879
#9      _InactiveElements._unmount.<anonymous closure>
package:flutter/…/widgets/framework.dart:1881
#10     ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4719
#11     _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1879
#12     _InactiveElements._unmount.<anonymous closure>
package:flutter/…/widgets/framework.dart:1881
#13     SingleChildRenderObjectElement.visitChildren
package:flutter/…/widgets/framework.dart:6182
#14     _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1879
#15     _InactiveElements._unmount.<anonymous closure>
package:flutter/…/widgets/framework.dart:1881
#16     SingleChildRenderObjectElement.visitChildren
package:flutter/…/widgets/framework.dart:6182
#17     _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1879
#18     _InactiveElements._unmount.<anonymous closure>
package:flutter/…/widgets/framework.dart:1881
#19     ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4719
#20     _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1879
#21     _InactiveElements._unmount.<anonymous closure>
package:flutter/…/widgets/framework.dart:1881
#22     MultiChildRenderObjectElement.visitChildren
package:flutter/…/widgets/framework.dart:6297
#23     _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1879
#24     _InactiveElements._unmount.<anonymous closure>
package:flutter/…/widgets/framework.dart:1881
#25     ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4719
#26     _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1879
#27     _InactiveElements._unmount.<anonymous closure>
package:flutter/…/widgets/framework.dart:1881
#28     SingleChildRenderObjectElement.visitChildren
package:flutter/…/widgets/framework.dart:6182
```

**Comment by DenisKen** [comment]
I'm getting this error too. Any updates?

**Comment by Ahmadre** [comment]
@rrousselGit

**Comment by Cayke** [comment]
Same here. Exception thrown when calling Provider inside Widget dispose method.

Flutter version: 2.5.1
Provider version: 6.0.0

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following _CastError was thrown while finalizing the widget tree:
flutter: Null check operator used on a null value
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Element.widget
flutter: #1      Provider._inheritedElementOf
flutter: #2      Provider.of
flutter: #3      _IBProductState.dispose
flutter: #4      StatefulElement.unmount
flutter: #5      _InactiveElements._unmount
flutter: #6      _InactiveElements._unmount.<anonymous closure>
flutter: #7      SingleChildRenderObjectElement.visitChildren
flutter: #8      _InactiveElements._unmount
flutter: #9      _InactiveElements._unmount.<anonymous closure>
flutter: #10     ComponentElement.visitChildren
flutter: #11     _InactiveElements._unmount
flutter: #12     _InactiveElements._unmount.<anonymous closure>
flutter: #13     SingleChildRenderObjectElement.visitChildren
flutter: #14     _InactiveElements._unmount
flutter: #15     _InactiveElements._unmount.<anonymous closure>
flutter: #16     SingleChildRenderObjectElement.visitChildren
flutter: #17     _InactiveElements._unmount
flutter: #18     _InactiveElements._unmount.<anonymous closure>
flutter: #19     ComponentElement.visitChildren
flutter: #20     _InactiveElements._unmount
flutter: #21     _InactiveElements._unmount.<anonymous closure>
flutter: #22     MultiChildRenderObjectElement.visitChildren
flutter: #23     _InactiveElements._unmount
flutter: #24     _InactiveElements._unmount.<anonymous closure>
flutter: #25     ComponentElement.visitChildren
flutter: #26     _InactiveElements._unmount
flutter: #27     _InactiveElements._unmount.<anonymous closure>
flutter: #28     SingleChildRenderObjectElement.visitChildren
flutter: #29     _InactiveElements._unmount
flutter: #30     _InactiveElements._unmount.<anonymous closure>
flutter: #31     ComponentElement.visitChildren
flutter: #32     _InactiveElements._unmount
flutter: #33     _InactiveElements._unmount.<anonymous closure>
flutter: #34     SingleChildRenderObjectElement.visitChildren
flutter: #35     _InactiveElements._unmount
flutter: #36     _InactiveElements._unmount.<anonymous closure>
flutter: #37     ComponentElement.visitChildren
flutter: #38     _InactiveElements._unmount
flutter: #39     _InactiveElements._unmount.<anonymous closure>
flutter: #40     SingleChildRenderObjectElement.visitChildren
flutter: #41     _InactiveElements._unmount
flutter: #42     _InactiveElements._unmount.<anonymous closure>
flutter: #43     ComponentElement.visitChildren
flutter: #44     _InactiveElements._unmount
flutter: #45     _InactiveElements._unmount.<anonymous closure>
flutter: #46     ComponentElement.visitChildren
flutter: #47     _InactiveElements._unmount
flutter: #48     _InactiveElements._unmount.<anonymous closure>
flutter: #49     ComponentElement.visitChildren
flutter: #50     _InactiveElements._unmount
flutter: #51     _InactiveElements._unmount.<anonymous closure>
flutter: #52     SingleChildRenderObjectElement.visitChildren
flutter: #53     _InactiveElements._unmount
flutter: #54     _InactiveElements._unmount.<anonymous closure>
flutter: #55     SingleChildRenderObjectElement.visitChildren
flutter: #56     _InactiveElements._unmount
flutter: #57     _InactiveElements._unmount.<anonymous closure>
flutter: #58     ComponentElement.visitChildren
flutter: #59     _InactiveElements._unmount
flutter: #60     _InactiveElements._unmount.<anonymous closure>
flutter: #61     SingleChildRenderObjectElement.visitChildren
flutter: #62     _InactiveElements._unmount
flutter: #63     _InactiveElements._unmount.<anonymous closure>
flutter: #64     ComponentElement.visitChildren
flutter: #65     _InactiveElements._unmount
flutter: #66     _InactiveElements._unmount.<anonymous closure>
flutter: #67     ComponentElement.visitChildren
flutter: #68     _InactiveElements._unmount
flutter: #69     _InactiveElements._unmount.<anonymous closure>
flutter: #70     ComponentElement.visitChildren
flutter: #71     _InactiveElements._unmount
flutter: #72     _InactiveElements._unmount.<anonymous closure>
flutter: #73     ComponentElement.visitChildren
flutter: #74     _InactiveElements._unmount
flutter: #75     _InactiveElements._unmount.<anonymous closure>
flutter: #76     ComponentElement.visitChildren
flutter: #77     _InactiveElements._unmount
flutter: #78     _InactiveElements._unmount.<anonymous closure>
flutter: #79     ComponentElement.visitChildren
flutter: #80     _InactiveElements._unmount
flutter: #81     _InactiveElements._unmount.<anonymous closure>
flutter: #82     SingleChildRenderObjectElement.visitChildren
flutter: #83     _InactiveElements._unmount
flutter: #84     _InactiveElements._unmount.<anonymous closure>
flutter: #85     ComponentElement.visitChildren
flutter: #86     _InactiveElements._unmount
flutter: #87     _InactiveElements._unmount.<anonymous closure>
flutter: #88     ComponentElement.visitChildren
flutter: #89     _InactiveElements._unmount
flutter: #90     _InactiveElements._unmount.<anonymous closure>
flutter: #91     ComponentElement.visitChildren
flutter: #92     _InactiveElements._unmount
flutter: #93     _InactiveElements._unmount.<anonymous closure>
flutter: #94     ComponentElement.visitChildren
flutter: #95     _InactiveElements._unmount
flutter: #96     _InactiveElements._unmount.<anonymous closure>
flutter: #97     ComponentElement.visitChildren
flutter: #98     _InactiveElements._unmount
flutter: #99     _InactiveElements._unmount.<anonymous closure>
flutter: #100    SingleChildRenderObjectElement.visitChildren
flutter: #101    _InactiveElements._unmount
flutter: #102    _InactiveElements._unmount.<anonymous closure>
flutter: #103    ComponentElement.visitChildren
flutter: #104    _InactiveElements._unmount
flutter: #105    _InactiveElements._unmount.<anonymous closure>
flutter: #106    ComponentElement.visitChildren
flutter: #107    _InactiveElements._unmount
flutter: #108    _InactiveElements._unmount.<anonymous closure>
flutter: #109    ComponentElement.visitChildren
flutter: #110    _InactiveElements._unmount
flutter: #111    _InactiveElements._unmount.<anonymous closure>
flutter: #112    MultiChildRenderObjectElement.visitChildren
flutter: #113    _InactiveElements._unmount
flutter: #114    _InactiveElements._unmount.<anonymous closure>
flutter: #115    ComponentElement.visitChildren
flutter: #116    _InactiveElements._unmount
flutter: #117    _InactiveElements._unmount.<anonymous closure>
flutter: #118    ComponentElement.visitChildren
flutter: #119    _InactiveElements._unmount
flutter: #120    _InactiveElements._unmount.<anonymous closure>
flutter: #121    ComponentElement.visitChildren
flutter: #122    _InactiveElements._unmount
flutter: #123    _InactiveElements._unmount.<anonymous closure>
flutter: #124    SingleChildRenderObjectElement.visitChildren
flutter: #125    _InactiveElements._unmount
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: Null check operator used on a null value
flutter:
#0      DiagnosticsNode.toString.<anonymous closure>
#1      DiagnosticsNode.toString
#2      StringBuffer.write (dart:core-patch/string_buffer_patch.dart:64:22)
#3      StringBuffer.writeAll (dart:core-patch/string_buffer_patch.dart:102:7)
#4      FirebaseCrashlytics.recordError
#5      FirebaseCrashlytics.recordFlutterError
#6      FlutterError.reportError
#7      SchedulerBinding.handleEventLoopCallback
#8      SchedulerBinding._runTasks
#9      _rootRun (dart:async/zone.dart:1420:47)
#10     _CustomZone.run (dart:async/zone.dart:1328:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#13     _rootRun (dart:async/zone.dart:1428:13)
#14     _CustomZone.run (dart:async/zone.dart:1328:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
#16     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
flutter: ----------------------------------------------------
flutter: #126    _InactiveElements._unmount.<anonymous closure>
flutter: #127    ComponentElement.visitChildren
flutter: #128    _InactiveElements._unmount
flutter: #129    _InactiveElements._unmount.<anonymous closure>
flutter: #130    SingleChildRenderObjectElement.visitChildren
flutter: #131    _InactiveElements._unmount
flutter: #132    _InactiveElements._unmount.<anonymous closure>
flutter: #133    SingleChildRenderObjectElement.visitChildren
flutter: #134    _InactiveElements._unmount
flutter: #135    _InactiveElements._unmount.<anonymous closure>
flutter: #136    ComponentElement.visitChildren
flutter: #137    _InactiveElements._unmount
flutter: #138    _InactiveElements._unmount.<anonymous closure>
flutter: #139    ComponentElement.visitChildren
flutter: #140    _InactiveElements._unmount
flutter: #141    _InactiveElements._unmount.<anonymous closure>
flutter: #142    ComponentElement.visitChildren
flutter: #143    _InactiveElements._unmount
flutter: #144    _InactiveElements._unmount.<anonymous closure>
flutter: #145    SingleChildRenderObjectElement.visitChildren
flutter: #146    _InactiveElements._unmount
flutter: #147    _InactiveElements._unmount.<anonymous closure>
flutter: #148    SingleChildRenderObjectElement.visitChildren
flutter: #149    _InactiveElements._unmount
flutter: #150    _InactiveElements._unmount.<anonymous closure>
flutter: #151    ComponentElement.visitChildren
flutter: #152    _InactiveElements._unmount
flutter: #153    _InactiveElements._unmount.<anonymous closure>
flutter: #154    SingleChildRenderObjectElement.visitChildren
flutter: #155    _InactiveElements._unmount
flutter: #156    _InactiveElements._unmount.<anonymous closure>
flutter: #157    SingleChildRenderObjectElement.visitChildren
flutter: #158    _InactiveElements._unmount
flutter: #159    _InactiveElements._unmount.<anonymous closure>
flutter: #160    ComponentElement.visitChildren
flutter: #161    _InactiveElements._unmount
flutter: #162    _InactiveElements._unmount.<anonymous closure>
flutter: #163    SingleChildRenderObjectElement.visitChildren
flutter: #164    _InactiveElements._unmount
flutter: #165    _InactiveElements._unmount.<anonymous closure>
flutter: #166    ComponentElement.visitChildren
flutter: #167    _InactiveElements._unmount
flutter: #168    _InactiveElements._unmount.<anonymous closure>
flutter: #169    SingleChildRenderObjectElement.visitChildren
flutter: #170    _InactiveElements._unmount
flutter: #171    _InactiveElements._unmount.<anonymous closure>
flutter: #172    SingleChildRenderObjectElement.visitChildren
flutter: #173    _InactiveElements._unmount
flutter: #174    _InactiveElements._unmount.<anonymous closure>
flutter: #175    ComponentElement.visitChildren
flutter: #176    _InactiveElements._unmount
flutter: #177    _InactiveElements._unmount.<anonymous closure>
flutter: #178    ComponentElement.visitChildren
flutter: #179    _InactiveElements._unmount
flutter: #180    _InactiveElements._unmount.<anonymous closure>
flutter: #181    SingleChildRenderObjectElement.visitChildren
flutter: #182    _InactiveElements._unmount
flutter: #183    _InactiveElements._unmount.<anonymous closure>
flutter: #184    ComponentElement.visitChildren
flutter: #185    _InactiveElements._unmount
flutter: #186    _InactiveElements._unmount.<anonymous closure>
flutter: #187    ComponentElement.visitChildren
flutter: #188    _InactiveElements._unmount
flutter: #189    _InactiveElements._unmount.<anonymous closure>
flutter: #190    SingleChildRenderObjectElement.visitChildren
flutter: #191    _InactiveElements._unmount
flutter: #192    _InactiveElements._unmount.<anonymous closure>
flutter: #193    SingleChildRenderObjectElement.visitChildren
flutter: #194    _InactiveElements._unmount
flutter: #195    _InactiveElements._unmount.<anonymous closure>
flutter: #196    ComponentElement.visitChildren
flutter: #197    _InactiveElements._unmount
flutter: #198    _InactiveElements._unmount.<anonymous closure>
flutter: #199    MultiChildRenderObjectElement.visitChildren
flutter: #200    _InactiveElements._unmount
flutter: #201    _InactiveElements._unmount.<anonymous closure>
flutter: #202    ComponentElement.visitChildren
flutter: #203    _InactiveElements._unmount
flutter: #204    _InactiveElements._unmount.<anonymous closure>
flutter: #205    ComponentElement.visitChildren
flutter: #206    _InactiveElements._unmount
flutter: #207    _InactiveElements._unmount.<anonymous closure>
flutter: #208    SingleChildRenderObjectElement.visitChildren
flutter: #209    _InactiveElements._unmount
flutter: #210    _InactiveElements._unmount.<anonymous closure>
flutter: #211    ComponentElement.visitChildren
flutter: #212    _InactiveElements._unmount
flutter: #213    _InactiveElements._unmount.<anonymous closure>
flutter: #214    ComponentElement.visitChildren
flutter: #215    _InactiveElements._unmount
flutter: #216    _InactiveElements._unmount.<anonymous closure>
flutter: #217    ComponentElement.visitChildren
flutter: #218    _InactiveElements._unmount
flutter: #219    _InactiveElements._unmount.<anonymous closure>
flutter: #220    ComponentElement.visitChildren
flutter: #221    _InactiveElements._unmount
flutter: #222    _InactiveElements._unmount.<anonymous closure>
flutter: #223    ComponentElement.visitChildren
flutter: #224    _InactiveElements._unmount
flutter: #225    _InactiveElements._unmount.<anonymous closure>
flutter: #226    ComponentElement.visitChildren
flutter: #227    _InactiveElements._unmount
flutter: #228    _InactiveElements._unmount.<anonymous closure>
flutter: #229    ComponentElement.visitChildren
flutter: #230    _InactiveElements._unmount
flutter: #231    _InactiveElements._unmount.<anonymous closure>
flutter: #232    SingleChildRenderObjectElement.visitChildren
flutter: #233    _InactiveElements._unmount
flutter: #234    _InactiveElements._unmount.<anonymous closure>
flutter: #235    SingleChildRenderObjectElement.visitChildren
flutter: #236    _InactiveElements._unmount
flutter: #237    _InactiveElements._unmount.<anonymous closure>
flutter: #238    ComponentElement.visitChildren
flutter: #239    _InactiveElements._unmount
flutter: #240    _InactiveElements._unmount.<anonymous closure>
flutter: #241    SingleChildRenderObjectElement.visitChildren
flutter: #242    _InactiveElements._unmount
flutter: #243    _InactiveElements._unmount.<anonymous closure>
flutter: #244    SingleChildRenderObjectElement.visitChildren
flutter: #245    _InactiveElements._unmount
flutter: #246    _InactiveElements._unmount.<anonymous closure>
flutter: #247    ComponentElement.visitChildren
flutter: #248    _InactiveElements._unmount
flutter: #249    _InactiveElements._unmount.<anonymous closure>
flutter: #250    ComponentElement.visitChildren
flutter: #251    _InactiveElements._unmount
flutter: #252    _InactiveElements._unmount.<anonymous closure>
flutter: #253    SingleChildRenderObjectElement.visitChildren
flutter: #254    _InactiveElements._unmount
flutter: #255    _InactiveElements._unmount.<anonymous closure>
flutter: #256    SingleChildRenderObjectElement.visitChildren
flutter: #257    _InactiveElements._unmount
flutter: #258    _InactiveElements._unmount.<anonymous closure>
flutter: #259    ComponentElement.visitChildren
flutter: #260    _InactiveElements._unmount
flutter: #261    _InactiveElements._unmount.<anonymous closure>
flutter: #262    SingleChildRenderObjectElement.visitChildren
flutter: #263    _InactiveElements._unmount
flutter: #264    _InactiveElements._unmount.<anonymous closure>
flutter: #265    ComponentElement.visitChildren
flutter: #266    _InactiveElements._unmount
flutter: #267    _InactiveElements._unmount.<anonymous closure>
flutter: #268    ComponentElement.visitChildren
flutter: #269    _InactiveElements._unmount
flutter: #270    _InactiveElements._unmount.<anonymous closure>
flutter: #271    ComponentElement.visitChildren
flutter: #272    _InactiveElements._unmount
flutter: #273    _InactiveElements._unmount.<anonymous closure>
flutter: #274    ComponentElement.visitChildren
flutter: #275    _InactiveElements._unmount
flutter: #276    _InactiveElements._unmount.<anonymous closure>
flutter: #277    ComponentElement.visitChildren
flutter: #278    _InactiveElements._unmount
flutter: #279    _InactiveElements._unmount.<anonymous closure>
flutter: #280    ComponentElement.visitChildren
flutter: #281    _InactiveElements._unmount
flutter: #282    _InactiveElements._unmount.<anonymous closure>
flutter: #283    SingleChildRenderObjectElement.visitChildren
flutter: #284    _InactiveElements._unmount
flutter: #285    _InactiveElements._unmount.<anonymous closure>
flutter: #286    ComponentElement.visitChildren
flutter: #287    _InactiveElements._unmount
flutter: #288    _InactiveElements._unmount.<anonymous closure>
flutter: #289    ComponentElement.visitChildren
flutter: #290    _InactiveElements._unmount
flutter: #291    _InactiveElements._unmount.<anonymous closure>
flutter: #292    ComponentElement.visitChildren
flutter: #293    _InactiveElements._unmount
flutter: #294    _InactiveElements._unmount.<anonymous closure>
flutter: #295    ComponentElement.visitChildren
flutter: #296    _InactiveElements._unmount
flutter: #297    _InactiveElements._unmount.<anonymous closure>
flutter: #298    ComponentElement.visitChildren
flutter: #299    _InactiveElements._unmount
flutter: #300    _InactiveElements._unmount.<anonymous closure>
flutter: #301    SingleChildRenderObjectElement.visitChildren
flutter: #302    _InactiveElements._unmount
flutter: #303    _InactiveElements._unmount.<anonymous closure>
flutter: #304    ComponentElement.visitChildren
flutter: #305    _InactiveElements._unmount
flutter: #306    _InactiveElements._unmount.<anonymous closure>
flutter: #307    ComponentElement.visitChildren
flutter: #308    _InactiveElements._unmount
flutter: #309    _InactiveElements._unmount.<anonymous closure>
flutter: #310    ComponentElement.visitChildren
flutter: #311    _InactiveElements._unmount
flutter: #312    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
flutter: #313    _InactiveElements._unmountAll
flutter: #314    BuildOwner.finalizeTree.<anonymous closure>
flutter: #315    BuildOwner.lockState
flutter: #316    BuildOwner.finalizeTree
flutter: #317    WidgetsBinding.drawFrame
flutter: #318    RendererBinding._handlePersistentFrameCallback
flutter: #319    SchedulerBinding._invokeFrameCallback
flutter: #320    SchedulerBinding.handleDrawFrame
flutter: #321    SchedulerBinding._handleDrawFrame
flutter: #325    _invoke (dart:ui/hooks.dart:166:10)
flutter: #326    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
flutter: #327    _drawFrame (dart:ui/hooks.dart:129:31)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a task callback:
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4276 pos 12: '_lifecycleState
flutter: != _ElementLifecycle.defunct': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      Element.markNeedsBuild
flutter: #3      State.setState
flutter: #4      _IBProductState.getProductInfoWidget.<anonymous closure>.<anonymous closure>
flutter: #5      VisibilityDetectorLayer._fireCallback
flutter: #6      VisibilityDetectorLayer._processCallbacks
flutter: #7      _TaskEntry.run.<anonymous closure>
flutter: #8      Timeline.timeSync (dart:developer/timeline.dart:163:22)
flutter: #9      _TaskEntry.run
flutter: #10     SchedulerBinding.handleEventLoopCallback
flutter: #11     SchedulerBinding._runTasks
flutter: (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter:
flutter:
flutter: This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack:
flutter: #0      new _TaskEntry.<anonymous closure>
flutter: #1      new _TaskEntry
flutter: #2      SchedulerBinding.scheduleTask
flutter: #3      VisibilityDetectorLayer._handleTimer
flutter: (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by rrousselGit** [comment]
I've looked into it. It's "expected" to fail. Although the error message should be different. 

It seems like "listen: false" makes the error message criptic. Without it, you'd get something among the lines of "calling depend on InheritedWidgets within the dispose method of a StatefulWidget as the context is unsafe, consider using didChangeDependencies blablabla".

**Comment by Cayke** [comment]
> I've looked into it. It's "expected" to fail. Although the error message should be different.
> 
> It seems like "listen: false" makes the error message criptic. Without it, you'd get something among the lines of "calling depend on InheritedWidgets within the dispose method of a StatefulWidget as the context is unsafe, consider using didChangeDependencies blablabla".

I need to call the provider on dispose method. It used to work on package versions before null safety. Do you a have a workaround to recommend @rrousselGit ?

**Comment by Zeswen** [comment]
Can reproduce. `Error thrown null` when calling `context.read`, it seems like we are not getting the `provider` errors logged.

Has this got any ETA?

**Comment by rrousselGit** [comment]
There's no ETA since this isn't a Provider bug

It's a bug in your program with a bad error message from Flutter

**Comment by Zeswen** [comment]
Oh nevermind, I though the error handling/error message was on Provider's side. My apologies.

**Comment by mdmota** [comment]
Any news?
I have a problem tbh. I initialize the providers in the initState using Provider.of . The Null check error only happens for some users when I try to use some provider method in my Future Builder method
